
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace RedBus_api.Models
{

using System;
    using System.Collections.Generic;
    
public partial class UltimaVIagemFilhoView
{

    public long idFilho { get; set; }

    public long idResponsavel { get; set; }

    public long idMotorista { get; set; }

    public string nome { get; set; }

    public Nullable<bool> emViagem { get; set; }

    public Nullable<bool> embarcado { get; set; }

    public Nullable<double> posicao_latitudeCasa { get; set; }

    public Nullable<double> posicao_longitutdeCasa { get; set; }

    public Nullable<double> posicao_latitudeEscola { get; set; }

    public Nullable<double> posicao_longitutdeEscola { get; set; }

    public byte[] foto { get; set; }

    public byte[] fotoCompleta { get; set; }

    public long idViagem { get; set; }

    public Nullable<System.DateTime> dataEmbarque { get; set; }

    public Nullable<System.DateTime> dataDesembarque { get; set; }

    public Nullable<double> posicaoEmbarque_latitude { get; set; }

    public Nullable<double> posicaoEmbarque_longitude { get; set; }

    public Nullable<double> posicaoDesembarque_latitude { get; set; }

    public Nullable<double> posicaoDesembarque_longitude { get; set; }

    public Nullable<double> posicao_latitude { get; set; }

    public Nullable<double> posicao_longitude { get; set; }

    public byte[] fotoMotorista { get; set; }

}

}
