//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RedBus_api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Viagem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Viagem()
        {
            this.Viagem_Filho = new HashSet<Viagem_Filho>();
        }
    
        public long idViagem { get; set; }
        public long idMotorista { get; set; }
        public System.DateTime dataInicioViagem { get; set; }
        public Nullable<System.DateTime> dataFimViagem { get; set; }
        public double posicaoInicio_latitude { get; set; }
        public double posicaoInicio_longitude { get; set; }
        public Nullable<double> posicaoFim_latitude { get; set; }
        public Nullable<double> posicaoFim_longitude { get; set; }
        public decimal statusViagem { get; set; }
    
        public virtual Motorista Motorista { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Viagem_Filho> Viagem_Filho { get; set; }
    }
}
